# Generated by Django 4.1.5 on 2023-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category ',
                'verbose_name_plural': 'Categories ',
                'db_table': 'Category',
            },
        ),
    ]
