# Generated by Django 4.1.5 on 2023-02-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_category_name_en_category_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Product name')),
                ('name_en', models.CharField(max_length=400, null=True, verbose_name='Product name')),
                ('name_uz', models.CharField(max_length=400, null=True, verbose_name='Product name')),
                ('image', models.ImageField(upload_to='product-images', verbose_name='Product image')),
                ('description', models.TextField(verbose_name='Product description')),
                ('description_en', models.TextField(null=True, verbose_name='Product description')),
                ('description_uz', models.TextField(null=True, verbose_name='Product description')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('discount', models.IntegerField(verbose_name='Product discount')),
                ('category', models.ManyToManyField(related_name='categories', to='products.category', verbose_name='Choose category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
