# Generated by Django 4.1.5 on 2023-02-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_product_table_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Product discount'),
        ),
    ]
